# Generated by Django 2.2.3 on 2019-07-05 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autor',
            name='correo',
            field=models.EmailField(max_length=254, verbose_name='E-mail'),
        ),
    ]
